### PR TITLE
fix: SPM manifest compilation on Swift 6.1

### LINKED ISSUE #7797: 8.58.1 — Package@swift-6.1.swift fails to compile on Xcode 16.3+ / Swift 6.1 (missing Foundation import)
### Platform

iOS, iPadOS, tvOS, macOS, watchOS, visionOS

### Environment

Develop

### Installed

Swift Package Manager

### Version

8.58.1

### Xcode Version

26.4

### Did it work on previous versions?

Yes — 8.58.0 and earlier. The failing file `Package@swift-6.1.swift` was introduced in 8.58.1 via #7784. 9.10.0 also works because the `getenv` block was removed during the 9.x refactor, so no 9.x release is affected.

### Steps to Reproduce

1. In any SwiftPM-based project, depend on sentry-cocoa with a range that can pick 8.58.1, e.g.:
   ```swift
   .package(url: "https://github.com/getsentry/sentry-cocoa.git", from: "8.40.1")
   ```
2. Delete `Package.resolved` (or use a fresh checkout) so SPM has to re-resolve.
3. Run `swift package resolve` on Xcode 26.4 (Swift 6.1).
   - Reproduces identically via `tuist install`.

### Expected Result

Manifest compiles and dependency resolution completes successfully.

### Actual Result

```
/Package@swift-6.1.swift:72:51: error: extra argument 'encoding' in call
   71 | let env = getenv("EXPERIMENTAL_SPM_BUILDS")
   72 | if let env = env, String(cString: env, encoding: .utf8) == "1" {
/Package@swift-6.1.swift:72:51: error: cannot infer contextual base in reference to member 'utf8'
```

`String(cString:encoding:)` and `String.Encoding.utf8` are Foundation APIs, but `Package@swift-6.1.swift` only imports `Darwin.C` and `PackageDescription` — Foundation is not available in the manifest evaluation context. The stdlib `String(cString:)` does not take an `encoding:` argument.

Minimal fix:

```swift
if let env = env, String(cString: env) == "1" {
```

`String(cString:)` already decodes as UTF-8, so behavior is preserved.

Workaround until a fix lands: pin `"8.40.1"..<"8.58.1"`.

### Are you willing to submit a PR?

Yes — proposed fix in #7800 (auto-closed due to missing issue reference; happy to reopen or submit a fresh PR once the approach is acknowledged).

### PR DESCRIPTION
**Pull request by WhiteHyun**
## :scroll: Description

Remove the `encoding:` argument from `String(cString:)` in `Package@swift-6.1.swift` so the manifest compiles on Swift 6.1 / Xcode 16+.

## :bulb: Motivation and Context

`String(cString:encoding:)` is a Foundation extension on `String` and is not available in the manifest context. On Swift 6.1 / Xcode 16+, manifest compilation fails with:

    /Package@swift-6.1.swift:72:51: error: extra argument 'encoding' in call
    /Package@swift-6.1.swift:72:51: error: cannot infer contextual base in reference to member 'utf8'

This breaks `swift package resolve` for downstream projects consuming affected 8.x versions on Xcode 16+.

The stdlib `String(cString:)` already decodes the C string as UTF-8, so behavior is preserved.

Fixes #7797

## :green_heart: How did you test it?

- `swift package dump-package` now succeeds on Xcode 16 / Swift 6.1.
- End-to-end dependency resolution was verified on a consumer project pinning sentry-cocoa in the 8.x range.

No unit tests added — this is a manifest-only change, and the current
test/CI setup does not include a dedicated manifest-compilation check.

## :pencil: Checklist

- [ ] I added tests to verify the changes.
- [x] No new PII added or SDK only sends newly added PII if `sendDefaultPII` is enabled.
- [x] I updated the docs if needed.
- [x] I updated the wizard if needed.
- [ ] Review from the native team if needed.
- [x] No breaking change or entry added to the changelog.
- [x] No breaking change for hybrid SDKs or communicated to hybrid SDKs.

### CODE REVIEW

**Comment by itaybre** [comment]
@WhiteHyun this looks good.

I am wondering if you can add a changelog entry to reflect this change so we can merge and release this on wednesday

**Comment by WhiteHyun** [comment]
@itaybre Added the changelog entry — thanks for the review!

**Review by itaybre — APPROVED** [review]
LGTM

**Comment by itaybre** [comment]
Looks like the checks fails due to permissions, I opened the same PR in https://github.com/getsentry/sentry-cocoa/pull/7819

We should be able to merge from there
