### ISSUE TITLE
Failing to compile on latest xcode 16 + 8.32

### ISSUE THREAD

**Issue by MattJustMatt** [getsentry/sentry-cocoa#4233]
### Platform

iOS, iPadOS

### Environment

Develop

### Installed

CocoaPods

### Version

8.32.0

### Xcode Version

16b

### Did it work on previous versions?

yes, 8.19

### Steps to Reproduce

Update to xcode beta, update to 8.32.0

### Expected Result

Compiles without breaking changes

### Actual Result

We had to update Sentry-Cocoa to address a compilation failure in xCode 16. 

Now we have two more errors:
```SentryId *tid = [[SentryId alloc] initWithUUIDString:ns_trace_id];```

Receiver 'SentryId' for class message is a forward declaration

```SentryEvent *event = [[SentryEvent alloc] initWithLevel:kSentryLevelWarning];```

Use of undeclared identifier 'kSentryLevelWarning'

### Are you willing to submit a PR?

Not familiar enough to say

**Comment by brustolin** [comment]
Hello @MattJustMatt, thanks for reaching out.
I could not reproduce this problem. Do you have anything different in your cocoapod setup?

Can you share the error log? I would like to see which files contain these errors.

**Comment by barisyild** [comment]
I have the same problem, but I don't use cocoapod :(

**Comment by brustolin** [comment]
@MattJustMatt, @barisyild, are you using Sentry in an Objc project?
Is the error in your own code when you're trying to use Sentry API`s?

We had reports of this error when users are importing sentry from the umbrella header instead of importing the module.

Instead of `#import <Sentry/Sentry.h>`
Use `@import Sentry;`

**Comment by kahest** [comment]
related docs PR: https://github.com/getsentry/sentry-docs/pull/10994

**Comment by MattJustMatt** [comment]
![Image](https://github.com/user-attachments/assets/eae1ba93-b89d-482a-9bab-6275e49811e8)

Ty! I made this adjustment, and updated to beta2, hitting this issue now. I'm sorry if this is noisy just made the mistake updating to Sequioa and locked into the new Xcode betas. 

If this is on Apple's end totally understand if we don't want to be supporting beta releases...

**Comment by harish-suthar** [comment]
@MattJustMatt I am facing a different issue on Xcode 16 beta 5?

![Image](https://github.com/user-attachments/assets/498ffde1-37b7-43b1-916f-e2ed6d29324b)

**Comment by brustolin** [comment]
@MattJustMatt, @harish-suthar. This was [fixed](https://github.com/getsentry/sentry-cocoa/pull/4244) already, we're releasing a new version today.

**Comment by brustolin** [comment]
We need to investigate whether is possible to keep using only `#import <Sentry/Sentry.h>`.

**Comment by MattJustMatt** [comment]
> We need to investigate whether it is possible to keep using only `#import <Sentry/Sentry.h>`.

This would be helpful. We have a cross platform app that loads the headers in a .cpp/.mm file and there may be some noise trying to get modules to work in this context, haven't investigated deeply yet

**Comment by MattJustMatt** [comment]
Turns out switching to modules is non trivial in our codebase (enabling the compiler flag for them causes all sorts of downstream issues). 

A header file import route would be very appreciated if it's possible!

**Comment by MattJustMatt** [comment]
![Image](https://github.com/user-attachments/assets/b14633ca-df3b-4047-b87c-ed0849b10173)

Good news! We managed to get past some of the include issues by adding the module compile flag to *just* our platform_interop.mm that includes Sentry. This is working on iOS but we're hitting a different error on M1 Macs/Arm64

**Comment by kahest** [comment]
Thanks for keeping us updated - we'll definitely look into providing a header import, but we don't have an ETA at the moment

**Comment by kahest** [comment]
We received feedback that the above workaround functions as intended - so we're closing this. If you're impacted by this and the above doesn't work, please let us know
