### ISSUE TITLE
SDK doesn't build with visionOS selected in Xcode 16.2

### ISSUE THREAD

**Issue by armcknight** [getsentry/sentry-cocoa#5051]
### Description

Possibly a swift 6 and C++ issue

```
/Users/andrewmcknight/Code/organization/getsentry/repos/public/sentry-cocoa/Sources/Swift/Integrations/Performance/IO/Data+SentryTracing.swift:21:62 'ReadingOptions' aliases 'Foundation.ReadingOptions' and cannot be used here because C++ types from imported module 'Foundation' do not support library evolution; this is an error in the Swift 6 language mode

Type declared here (Foundation.NSData)
/Users/andrewmcknight/Code/organization/getsentry/repos/public/sentry-cocoa/Sources/Swift/Integrations/Performance/IO/Data+SentryTracing.swift:52:60 'WritingOptions' aliases 'Foundation.WritingOptions' and cannot be used here because C++ types from imported module 'Foundation' do not support library evolution; this is an error in the Swift 6 language mode

Type declared here (Foundation.NSData)
```

**Comment by philipphofmann** [comment]
I can compile the visionOS-Swift sample, when commenting out the `option.profilesSampleRate`. I will open a PR to remove this option. What exactly do you do @armcknight, so we can reproduce this?

**Comment by philipphofmann** [comment]
Ah when I try building the sample in CI, we get

```
/Users/runner/work/sentry-cocoa/sentry-cocoa/Sources/Swift/Integrations/Performance/IO/Data+SentryTracing.swift:21:62: error: 'ReadingOptions' aliases 'Foundation.ReadingOptions' and cannot be used here because C++ types from imported module 'Foundation' do not support library evolution; this is an error in the Swift 6 language mode
    init(contentsOfWithSentryTracing url: URL, options: Data.ReadingOptions = []) throws {
                                                             ^
Foundation.NSData:2:19: note: type declared here
    public struct ReadingOptions : OptionSet, @unchecked Sendable {
                  ^
/Users/runner/work/sentry-cocoa/sentry-cocoa/Sources/Swift/Integrations/Performance/IO/Data+SentryTracing.swift:52:60: error: 'WritingOptions' aliases 'Foundation.WritingOptions' and cannot be used here because C++ types from imported module 'Foundation' do not support library evolution; this is an error in the Swift 6 language mode
    func writeWithSentryTracing(to url: URL, options: Data.WritingOptions = []) throws {
                                                           ^
Foundation.NSData:35:19: note: type declared here
    public struct WritingOptions : OptionSet, @unchecked Sendable {
```

**Comment by philprime** [comment]
We also need to investigate why does the CI which is testing Swift 6 support is not failing.
