### ISSUE TITLE
8.58.1 — Package@swift-6.1.swift fails to compile on Xcode 16.3+ / Swift 6.1 (missing Foundation import)

### ISSUE THREAD

**Issue by WhiteHyun** [getsentry/sentry-cocoa#7797]
### Platform

iOS, iPadOS, tvOS, macOS, watchOS, visionOS

### Environment

Develop

### Installed

Swift Package Manager

### Version

8.58.1

### Xcode Version

26.4

### Did it work on previous versions?

Yes — 8.58.0 and earlier. The failing file `Package@swift-6.1.swift` was introduced in 8.58.1 via #7784. 9.10.0 also works because the `getenv` block was removed during the 9.x refactor, so no 9.x release is affected.

### Steps to Reproduce

1. In any SwiftPM-based project, depend on sentry-cocoa with a range that can pick 8.58.1, e.g.:
   ```swift
   .package(url: "https://github.com/getsentry/sentry-cocoa.git", from: "8.40.1")
   ```
2. Delete `Package.resolved` (or use a fresh checkout) so SPM has to re-resolve.
3. Run `swift package resolve` on Xcode 26.4 (Swift 6.1).
   - Reproduces identically via `tuist install`.

### Expected Result

Manifest compiles and dependency resolution completes successfully.

### Actual Result

```
/Package@swift-6.1.swift:72:51: error: extra argument 'encoding' in call
   71 | let env = getenv("EXPERIMENTAL_SPM_BUILDS")
   72 | if let env = env, String(cString: env, encoding: .utf8) == "1" {
/Package@swift-6.1.swift:72:51: error: cannot infer contextual base in reference to member 'utf8'
```

`String(cString:encoding:)` and `String.Encoding.utf8` are Foundation APIs, but `Package@swift-6.1.swift` only imports `Darwin.C` and `PackageDescription` — Foundation is not available in the manifest evaluation context. The stdlib `String(cString:)` does not take an `encoding:` argument.

Minimal fix:

```swift
if let env = env, String(cString: env) == "1" {
```

`String(cString:)` already decodes as UTF-8, so behavior is preserved.

Workaround until a fix lands: pin `"8.40.1"..<"8.58.1"`.

### Are you willing to submit a PR?

Yes — proposed fix in #7800 (auto-closed due to missing issue reference; happy to reopen or submit a fresh PR once the approach is acknowledged).

**Comment by WhiteHyun** [comment]
I've opened PR #7800 with a minimal fix for this. It was auto-closed by the bot because the PR body didn't reference this issue — apologies for the oversight.

Happy to either have a maintainer reopen #7800, or I can open a fresh PR referencing this issue once the proposed approach is acknowledged.
Let me know which you prefer
