### ISSUE TITLE
initWithDsnString

### ISSUE THREAD

**Issue by andershagebakken** [getsentry/sentry-cocoa#146]
_Platform:_ 
- [x]  iOS 
- [ ]  tvOS
- [ ]  MacOS 
- [ ]  watchOS

_Swift:_
- [ ]  Yes -> If yes, which version? 
- [x]  No

_sentry-swift installed with:_
- [ ] Cocoapods
- [ ] Carthage
- [x] Manually

Version of sentry-swift:
**2.1.7**

---
I have following issue:

For some reason, my app suddenly crashes at initWithDsnString. I implemented Sentry for two-three weeks ago, and everything has been working smoothly until today. I tried to upgrade Sentry-swift and KSCrash to the lastest version, but it still crashes at the same spot. 

**Steps to reproduce:**
- initWithDsnString

<img width="248" alt="skjermbilde 2017-04-06 13 16 00" src="https://cloud.githubusercontent.com/assets/8410327/24751881/87527910-1acb-11e7-8b5f-6c4cad1ceb16.png">

    0x10044c840 <+128>:  add    x8, x28, x8
    0x10044c844 <+132>:  str    x8, [sp, #0x38]
    0x10044c848 <+136>:  stp    xzr, xzr, [x8]
    0x10044c84c <+140>:  str    xzr, [x8, #0x10]
    0x10044c850 <+144>:  strb   w9, [x8, #0x18]
    0x10044c854 <+148>:  nop    
    0x10044c858 <+152>:  ldr    x22, #0x3f8b0             ; (void *)0x0000000100c09468: _swiftEmptyArrayStorage
    0x10044c85c <+156>:  mov    x0, x22
    0x10044c860 <+160>:  bl     0x100428fb4               ; rt_swift_retain
    0x10044c864 <+164>:  sub    x8, x29, #0x78            ; =0x78*
    0x10044c868 <+168>:  mov    x0, x22
    0x10044c86c <+172>:  bl     0x100428a18               ; function signature specialization <Arg[0] = Owned To Guaranteed, Arg[1] = Dead> of generic specialization <Swift.String with Swift.String : Swift.Hashable in Swift, Swift.String> of static Swift._NativeDictionaryStorage.fromArray (Swift.Array<(A, B)>) -> Swift._NativeDictionaryStorage<A, B> at Contexts.swift
    0x10044c870 <+176>:  ldp    x19, x24, [x29, #-0x78]
    0x10044c874 <+180>:  ldp    x25, x26, [x29, #-0x68]

It crashes on the line:
**0x10044c864 <+164>:  sub    x8, x29, #0x78            ; =0x78** 

How can I fix this to get it to work again?

**Comment by HazAT** [comment]
Can you double check your code, since we haven't changed anything recently in the init process.

**Comment by andershagebakken** [comment]
The problem is that I have not touched a thing since it worked the last time, which is why i am stumped.

**Comment by HazAT** [comment]
Could it be that you updated to Xcode 8.3? Did you do a clean build? `CMD+Shift+Alt+K`

**Comment by andershagebakken** [comment]
Yes, it turns out I have XCode 8.3 now. I tried deleted DerivedData and did a clean. It did not help. Is there something I have to do to get it work in 8.3? Thanks.

**Comment by HazAT** [comment]
I have a objc project running locally with the latest version which works without any problems.
Using swift3 for compiling sentry (which you have to because xcode 8.3 does no longer support swift 2.3)

**Comment by andershagebakken** [comment]
Thank you for your time. I am getting a more elaborated error message now:
```
dyld: Symbol not found: __TMaCs28_NativeDictionaryStorageImpl
  Referenced from: /.../.../Frameworks/Sentry.framework/Sentry
  Expected in: /.../.../Frameworks/libswiftCore.dylib
```
Just to be sure, the KSCrash og Sentry frameworks should be added to "Copy Files", and not Embed Framework, or Link Binary with Libraries? Is there any other configuration needed in XCode? I just think it is strange that it suddenly now crashes, just because of the Xcode update.

**Comment by HazAT** [comment]
please make sure following settings are the same in all your targets.
<img width="463" alt="screen shot 2017-04-07 at 10 03 40" src="https://cloud.githubusercontent.com/assets/363802/24791205/94183f8c-1b79-11e7-88b7-b6587787f6f5.png">
<img width="475" alt="screen shot 2017-04-07 at 10 03 49" src="https://cloud.githubusercontent.com/assets/363802/24791209/96db2e32-1b79-11e7-91d9-9b749c0c650b.png">

**Comment by andershagebakken** [comment]
Thanks, but I am trying to use it in a Objective-C project, so I assume there might be a different configuration needed? Before it stopped working, the only thing I changed was "Always embed swift standard libraries", and set it to Yes. I

**Comment by corybu** [comment]
I am in the exact same situation.  I have an Objective-C project and the app started crashing upon launch as soon as I updated to Xcode 8.3.1 (from 8.2).  I tried updating to the latest Sentry with no luck.  I have been unable to figure out a configuration that works.

**Comment by HazAT** [comment]
Hey,
We've just released version `3.0.0` which is a rewrite in objc, please consider upgrading the errors should be gone.
